[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
  "npm install",
  "cd server && npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd server && npx prisma generate",
  "cd server && npm run build",
  "cd client && npm run build"
]

[start]
cmd = "npm start"
